spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cards
    username: postgres
    password: postgre

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update

  mvc:
    validation: true
